apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flagd-sync-token
  namespace: techx-tf3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: flagd-sync-token
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: techx-corp-tf3/flagd-sync-token
