apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: techx-tf3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin-user
      remoteRef:
        key: techx-corp-tf3/grafana-admin-credentials
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: techx-corp-tf3/grafana-admin-credentials
        property: admin-password
