# PVC cho Postgres (Mandate #2, Reliability — chống mất data khi pod restart/reschedule).
# Chart chỉ tự tạo PVC cho valkey (valkey-cart-pvc.yaml); postgres + kafka khai riêng ở đây.
# Kafka: image apache/kafka tự format KRaft bằng CLUSTER_ID cố định khi log dir trống (verify
# ở launch script - idempotent, "already formatted" thì skip) -> PVC trống được format tự động.
#
# storageClass gp2 (WaitForFirstConsumer — bind khi pod schedule, đúng AZ). RWO: chỉ 1 pod mount
# tại 1 thời điểm -> component postgres phải dùng strategy: Recreate (đã set trong values-prod.yaml).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: techx-tf3
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/part-of: techx-corp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: techx-tf3
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: techx-corp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 3Gi
