apiVersion: v1
kind: LimitRange
metadata:
  name: techx-limits
  namespace: techx-tf3
spec:
  limits:
    - default:
        cpu: "200m"
        memory: "150Mi"
      defaultRequest:
        cpu: "100m"
        memory: "50Mi"
      type: Container
