apiVersion: v1
kind: LimitRange
metadata:
  name: techx-limits
  namespace: techx-tf3
spec:
  limits:
    - type: Container
      min:
        cpu: "5m"
        memory: "8Mi"
      max:
        cpu: "4"
        memory: "4Gi"
