apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opensearch-access
  namespace: techx-tf3
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: opensearch
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: fluent-bit
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: jaeger
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: opentelemetry-collector
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: otel-gateway
        - podSelector:
            matchLabels:
              app: aiops-engine
      ports:
        - protocol: TCP
          port: 9200
