apiVersion: v1
kind: ResourceQuota
metadata:
  name: techx-quota
  namespace: techx-tf3
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 16Gi
    limits.cpu: "48"
    limits.memory: 30Gi
    pods: "100"
