apiVersion: v1
kind: Pod
metadata:
  name: mandate05-native-bad-latest
  namespace: techx-tf3
  labels:
    app.kubernetes.io/name: mandate05-native-bad-latest
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: nginx:latest
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
