apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-proxy-internal
  namespace: techx-tf3
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: techx-tf3-frontend-internal
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/security-groups: techx-corp-tf3-internal-alb
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-proxy
                port:
                  number: 8080
