apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-platform-egress
  namespace: techx-tf3
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
    - to:
        - ipBlock: { cidr: 172.20.0.1/32 }
        - ipBlock: { cidr: 10.0.0.0/16 }
      ports:
        - { protocol: TCP, port: 443 }
