apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagd-secret-sync
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tuu-ngo/Phase3-TF3-Infra-Sentinel.git'
    targetRevision: deploy/account-migration-gitops
    path: gitops/secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: techx-tf3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
