apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.14.0
    helm:
      values: |
        serviceAccount:
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::197826770971:role/techx-corp-tf3-karpenter-controller
        settings:
          clusterName: techx-corp-tf3
          interruptionQueue: techx-corp-tf3-karpenter
        controller:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
