apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tuu-ngo/Phase3-TF3-Infra-Sentinel.git'
    targetRevision: deploy/account-migration-gitops
    path: gitops/karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
