apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.3.4
    helm:
      values: |
        admissionController:
          replicas: 1
          rbac:
            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::197826770971:role/techx-corp-tf3-kyverno-ecr
          container:
            resources:
              requests:
                cpu: 100m
              limits:
                cpu: 1000m
        backgroundController:
          replicas: 1
          rbac:
            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::197826770971:role/techx-corp-tf3-kyverno-ecr
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
        reportsController:
          replicas: 1
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
        cleanupController:
          replicas: 1
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 200m
        policyReportsCleanup:
          image:
            repository: bitnamilegacy/kubectl
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
