apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techx-corp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tuu-ngo/Phase3-TF3-Infra-Sentinel.git'
    targetRevision: main
    path: phase3 - information/techx-corp-chart
    helm:
      valueFiles:
        - values.yaml
        - ../deploy/values-flagd-sync.yaml
        - ../deploy/values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: techx-tf3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
